/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AddFrames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daria
 */
public class AddOddzialy extends javax.swing.JFrame {

    private String PASS, USER, ID;
    private ResultSet rs;
    
    public AddOddzialy(String pass, String user) 
    {
        initComponents();
        PASS = pass;
        USER = user;
     
    }
    
    public int CheckIP()
    {
        int a = 1;
        ArrayList data = new ArrayList();
        try 
                {   
                    Class.forName("oracle.jdbc.OracleDriver").newInstance();
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    Statement st = con.createStatement();

                    String sql = "SELECT * FROM ODDZIALY_BANKOWE";
                    rs = st.executeQuery(sql);
                    
                    while(rs.next())    
                    {
                    int id_poczty = rs.getInt("ID_ODDZIALU");
                    data.add(id_poczty);
                    }
                    
                    st.close();
                    con.close();
                    dispose();
                }
        catch(Exception e) {JOptionPane.showMessageDialog(null, e);}
        
        for(int j =0;j<=data.size()-1;j++)
        {
        for(int i =0;i<=data.size()-1;i++)
        {
              Object n = data.get(i);
              if(a == (int)n) {a++;}
      
        }}

        return a;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTytul = new javax.swing.JLabel();
        LabelPKod = new javax.swing.JLabel();
        LabelUlica = new javax.swing.JLabel();
        LabelNrBudynku = new javax.swing.JLabel();
        LabelZalozenie = new javax.swing.JLabel();
        LabelTelefon = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        ButtonDodaj = new javax.swing.JButton();
        ButtonAnuluj = new javax.swing.JButton();
        FieldKPocztowy = new javax.swing.JTextField();
        FieldUlica = new javax.swing.JTextField();
        FieldNrBudynku = new javax.swing.JTextField();
        FieldTelefon = new javax.swing.JTextField();
        FieldMail = new javax.swing.JTextField();
        BoxDay = new javax.swing.JComboBox<>();
        BoxMon = new javax.swing.JComboBox<>();
        BoxYear = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        LabelTytul.setText("DODAWANIE NOWEGO ODDZIAŁU");

        LabelPKod.setText("KOD POCZTOWY");

        LabelUlica.setText("ULICA");

        LabelNrBudynku.setText("NR BUDYNKU");

        LabelZalozenie.setText("DATA ZAŁOŻENIA");

        LabelTelefon.setText("NUMER TELEFONU");

        LabelEmail.setText("EMAIL");

        ButtonDodaj.setText("DODAJ");
        ButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDodajActionPerformed(evt);
            }
        });

        ButtonAnuluj.setText("ANULUJ");
        ButtonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnulujActionPerformed(evt);
            }
        });

        BoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BoxMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        BoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2020", "2021", "2022" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTytul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTelefon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelZalozenie, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNrBudynku, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FieldNrBudynku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldTelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelUlica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelPKod)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonDodaj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonAnuluj)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldKPocztowy, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LabelTytul)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPKod)
                    .addComponent(FieldKPocztowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUlica)
                    .addComponent(FieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNrBudynku)
                    .addComponent(FieldNrBudynku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelZalozenie)
                    .addComponent(BoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefon)
                    .addComponent(FieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(FieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDodaj)
                    .addComponent(ButtonAnuluj))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnulujActionPerformed
              dispose();
    }//GEN-LAST:event_ButtonAnulujActionPerformed

    private void ButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDodajActionPerformed
       
       

        String Kod_pocztowy = FieldKPocztowy.getText();
        String Mail = FieldMail.getText();
       // String Miejscowosc = FieldMiejscowosc.getText();
        String NrBudynku = FieldNrBudynku.getText();
        String Telefon = FieldTelefon.getText();
        String Ulica = FieldUlica.getText();
        String DataZalozenia = BoxDay.getSelectedItem() + "-" + BoxMon.getSelectedItem() + "-" +BoxYear.getSelectedItem();
        int ID = CheckIP();
        int ID_POCZTY = 0;
        
        try
        {
            Class.forName("oracle.jdbc.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
            Statement st = con.createStatement();
                
            String sql = "SELECT * FROM POCZTY WHERE KOD_POCZTOWY =" + "'"+Kod_pocztowy+"'";
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                ID_POCZTY = rs.getInt("ID_POCZTY");
            }
           
            if (ID_POCZTY != 0) 
            { 
                String Query = "INSERT INTO ODDZIALY_BANKOWE (ID_ODDZIALU, ID_BANKU, ID_POCZTY, ULICA, NR_BUDYNKU, DATA_ZALOZENIA, NUMER_KONTAKTOWY,MAIL) "
                           + "VALUES ('"+ID+"', '"+1+"','"+ID_POCZTY+"','"+Ulica+"', '"+NrBudynku+"', '"+DataZalozenia+"','"+Telefon+"', '"+Mail+"')";
        
                st.execute(Query);
                JOptionPane.showMessageDialog(null, "Dodano nowy oddział");
                st.close();
                con.close();
                dispose();
            }
            else {JOptionPane.showMessageDialog(null, "Brak poczty w bazie, najpierw dodaj poczte");}
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        FieldKPocztowy.setText("");
        FieldMail.setText("");
        FieldNrBudynku.setText("");
        FieldTelefon.setText("");
        FieldUlica.setText("");
        // String DataZalozenia = BoxDay.getSelectedItem() + "-" + BoxMon.getSelectedItem() + "-" +BoxYear.getSelectedItem();
       
    }//GEN-LAST:event_ButtonDodajActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxDay;
    private javax.swing.JComboBox<String> BoxMon;
    private javax.swing.JComboBox<String> BoxYear;
    private javax.swing.JButton ButtonAnuluj;
    private javax.swing.JButton ButtonDodaj;
    private javax.swing.JTextField FieldKPocztowy;
    private javax.swing.JTextField FieldMail;
    private javax.swing.JTextField FieldNrBudynku;
    private javax.swing.JTextField FieldTelefon;
    private javax.swing.JTextField FieldUlica;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNrBudynku;
    private javax.swing.JLabel LabelPKod;
    private javax.swing.JLabel LabelTelefon;
    private javax.swing.JLabel LabelTytul;
    private javax.swing.JLabel LabelUlica;
    private javax.swing.JLabel LabelZalozenie;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
