/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AddFrames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daria
 */
public class AddPoczta extends javax.swing.JFrame {

    private String PASS,USER;
    private ResultSet rs;
    //private ArrayList arl;
    
    public AddPoczta(String pass, String user) {
        initComponents();
        PASS = pass;
        USER = user;
    }

    public int CheckIP()
    {
        int a = 1;
        ArrayList data = new ArrayList();
        try 
                {   
                    Class.forName("oracle.jdbc.OracleDriver").newInstance();
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    Statement st = con.createStatement();

                    String sql = "SELECT * FROM POCZTY";
                    rs = st.executeQuery(sql);
                    
                    while(rs.next())    
                    {
                    int id_poczty = rs.getInt("ID_POCZTY");
                    data.add(id_poczty);
                    }
                    
                    st.close();
                    con.close();
                    dispose();
                }
        catch(Exception e) {JOptionPane.showMessageDialog(null, e);}
        
        for(int j =0;j<=data.size()-1;j++)
        {
        for(int i =0;i<=data.size()-1;i++)
        {
              Object n = data.get(i);
              if(a == (int)n) {a++;}
      
        }}

        return a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabellTytyul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FieldMiejscowosc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FieldPoczta = new javax.swing.JTextField();
        ButtonDodaj = new javax.swing.JButton();
        ButtonAnuluj = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        LabellTytyul.setText("DODWAWANIE NOWEJ POCZTY");

        jLabel1.setText("MIEJSCOWOŚĆ");

        FieldMiejscowosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMiejscowoscActionPerformed(evt);
            }
        });

        jLabel2.setText("KOD POCZTOWY");

        ButtonDodaj.setText("DODAJ");
        ButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDodajActionPerformed(evt);
            }
        });

        ButtonAnuluj.setText("ANULUJ");
        ButtonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabellTytyul)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(FieldMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ButtonDodaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAnuluj)
                            .addComponent(FieldPoczta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabellTytyul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FieldMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldPoczta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDodaj)
                    .addComponent(ButtonAnuluj))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnulujActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonAnulujActionPerformed

    private void ButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDodajActionPerformed
       
       int ID = CheckIP();
      
       String Miejscowosc = FieldMiejscowosc.getText();
       String Kod_pocztowy = FieldPoczta.getText();
       
       try 
                {   
                    Class.forName("oracle.jdbc.OracleDriver").newInstance();
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    Statement st = con.createStatement();

                    String Query = "INSERT INTO POCZTY (ID_POCZTY, MIEJSCOWOSC, KOD_POCZTOWY) "
                           + "VALUES ('"+ID+"','"+Miejscowosc+"','"+Kod_pocztowy+"')";
                    
                    st.execute(Query);
                    JOptionPane.showMessageDialog(null, "Dodano nową pocztę");
                    st.close();
                    con.close();
                    dispose();
                }
            catch(Exception e) {JOptionPane.showMessageDialog(null, e);}
                    
            FieldMiejscowosc.setText("");
            FieldPoczta.setText("");
                
       
       
    }//GEN-LAST:event_ButtonDodajActionPerformed

    private void FieldMiejscowoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMiejscowoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMiejscowoscActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnuluj;
    private javax.swing.JButton ButtonDodaj;
    private javax.swing.JTextField FieldMiejscowosc;
    private javax.swing.JTextField FieldPoczta;
    private javax.swing.JLabel LabellTytyul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
