/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AddFrames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daria
 */
public class AddUrzadzenie extends javax.swing.JFrame {

    private String PASS, USER;
    private ResultSet rs;
    
    public AddUrzadzenie(String pass, String user) {
        initComponents();
        
        PASS = pass;
        USER = user;
    }
    
    public int CheckIP()
    {
        int a = 1;
        ArrayList data = new ArrayList();
        try 
                {   
                    Class.forName("oracle.jdbc.OracleDriver").newInstance();
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    Statement st = con.createStatement();

                    String sql = "SELECT * FROM URZADZENIA_ZEWNETRZNE";
                    rs = st.executeQuery(sql);
                    
                    while(rs.next())    
                    {
                    int id_poczty = rs.getInt("ID_URZADZENIA");
                    data.add(id_poczty);
                    }
                    
                    st.close();
                    con.close();
                    dispose();
                }
        catch(Exception e) {JOptionPane.showMessageDialog(null, e);}
        
        for(int j =0;j<=data.size()-1;j++)
        {
        for(int i =0;i<=data.size()-1;i++)
        {
              Object n = data.get(i);
              if(a == (int)n) {a++;}
      
        }}

        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTyp = new javax.swing.JLabel();
        LabelMiejscowosc = new javax.swing.JLabel();
        FieldMiejscowosc = new javax.swing.JTextField();
        LabelUlica = new javax.swing.JLabel();
        FieldUlica = new javax.swing.JTextField();
        LabelUzupelnienie = new javax.swing.JLabel();
        LabelKonserwacja = new javax.swing.JLabel();
        LabelNrBudynku = new javax.swing.JLabel();
        FieldNrBudynku = new javax.swing.JTextField();
        LabelOpisLokalizacji = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLokalizacja = new javax.swing.JTextArea();
        ButtonDodaj = new javax.swing.JButton();
        ButtonAnuluj = new javax.swing.JButton();
        LabelAddNoweU = new javax.swing.JLabel();
        ComboBoxTyp = new javax.swing.JComboBox<>();
        BoxDay1 = new javax.swing.JComboBox<>();
        BoxMon1 = new javax.swing.JComboBox<>();
        BoxYear1 = new javax.swing.JComboBox<>();
        BoxDay2 = new javax.swing.JComboBox<>();
        BoxMon2 = new javax.swing.JComboBox<>();
        BoxYear2 = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelTyp.setText("TYP");

        LabelMiejscowosc.setText("MIEJSCOWOŚĆ");

        LabelUlica.setText("ULICA");

        LabelUzupelnienie.setText("OSTATNIE UZUPEŁNIENIE");

        LabelKonserwacja.setText("OSTATNIA KONSERWACJA");

        LabelNrBudynku.setText("NUMER BUDYNKU");

        LabelOpisLokalizacji.setText("OPIS LOKALIZACJI");

        TextLokalizacja.setColumns(20);
        TextLokalizacja.setRows(5);
        TextLokalizacja.setText("\n");
        jScrollPane1.setViewportView(TextLokalizacja);

        ButtonDodaj.setText("DODAJ");
        ButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDodajActionPerformed(evt);
            }
        });

        ButtonAnuluj.setText("ANULUJ");
        ButtonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnulujActionPerformed(evt);
            }
        });

        LabelAddNoweU.setText("DODAJ NOWE URZĄDZENIE");

        ComboBoxTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bankomat", "Wpłatomat", "Bankomat/Wpłatomat" }));

        BoxDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BoxMon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        BoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2020", "2021", "2022" }));

        BoxDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BoxMon2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        BoxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2020", "2021", "2022" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAddNoweU)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonDodaj)
                        .addGap(42, 42, 42)
                        .addComponent(ButtonAnuluj))
                    .addComponent(LabelOpisLokalizacji)
                    .addComponent(LabelNrBudynku)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelUlica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelMiejscowosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LabelUzupelnienie)
                            .addComponent(LabelKonserwacja))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(FieldNrBudynku, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FieldUlica, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FieldMiejscowosc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboBoxTyp, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(LabelAddNoweU)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMiejscowosc)
                    .addComponent(FieldMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUlica)
                    .addComponent(FieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUzupelnienie)
                    .addComponent(BoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKonserwacja)
                    .addComponent(BoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNrBudynku)
                    .addComponent(FieldNrBudynku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelOpisLokalizacji)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDodaj)
                    .addComponent(ButtonAnuluj))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnulujActionPerformed
       
        dispose();
    }//GEN-LAST:event_ButtonAnulujActionPerformed

    private void ButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDodajActionPerformed
       
        int ID = CheckIP();
        try 
                {   
                    Class.forName("oracle.jdbc.OracleDriver").newInstance();
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    Statement st = con.createStatement();
                    
                    String Uzupelnienie = BoxDay1.getSelectedItem() + "-" + BoxMon1.getSelectedItem() + "-" +BoxYear1.getSelectedItem();
                    String Konserwacja = BoxDay2.getSelectedItem() + "-" + BoxMon2.getSelectedItem() + "-" +BoxYear2.getSelectedItem();
                    
                    String sql;
                    sql = "INSERT INTO \"URZADZENIA_ZEWNETRZNE\" VALUES ('"+ID+"',"
                            + " '"+ComboBoxTyp.getSelectedItem()+"' , '"+FieldMiejscowosc.getText()+"',"
                            + "'"+FieldUlica.getText()+"', '"+FieldNrBudynku.getText()+"','"+TextLokalizacja.getText()+"',"
                            + " '"+Uzupelnienie+"','"+Konserwacja+"', '"+1+"')";
                    st.execute(sql);
            
                    st.close();
                    con.close();
           
                    JOptionPane.showMessageDialog(null, "Dodano nowe urządzenie");
                    dispose();
                }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);} 
        
        
        FieldMiejscowosc.setText("");
        FieldUlica.setText("");
        FieldNrBudynku.setText("");
        TextLokalizacja.setText("");
    }//GEN-LAST:event_ButtonDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxDay1;
    private javax.swing.JComboBox<String> BoxDay2;
    private javax.swing.JComboBox<String> BoxMon1;
    private javax.swing.JComboBox<String> BoxMon2;
    private javax.swing.JComboBox<String> BoxYear1;
    private javax.swing.JComboBox<String> BoxYear2;
    private javax.swing.JButton ButtonAnuluj;
    private javax.swing.JButton ButtonDodaj;
    private javax.swing.JComboBox<String> ComboBoxTyp;
    private javax.swing.JTextField FieldMiejscowosc;
    private javax.swing.JTextField FieldNrBudynku;
    private javax.swing.JTextField FieldUlica;
    private javax.swing.JLabel LabelAddNoweU;
    private javax.swing.JLabel LabelKonserwacja;
    private javax.swing.JLabel LabelMiejscowosc;
    private javax.swing.JLabel LabelNrBudynku;
    private javax.swing.JLabel LabelOpisLokalizacji;
    private javax.swing.JLabel LabelTyp;
    private javax.swing.JLabel LabelUlica;
    private javax.swing.JLabel LabelUzupelnienie;
    private javax.swing.JTextArea TextLokalizacja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
