/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelsEntity;

import AddFrames.AddPoczta;
import AddFrames.UpdatePoczta;
import static PanelsEntity.Oddzialy.st;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daria
 */
public class Poczta extends javax.swing.JPanel {

    String PASS,USER;
    private AddPoczta AddP;
    private Connection con;
    private Statement st;
    private ResultSet Res;
    private UpdatePoczta UpDate;
    
    public Poczta(String pass, String user) {
        initComponents();
        
        USER = user;
        PASS = pass;
        AddP = new AddPoczta(PASS, USER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaDanych = new javax.swing.JTable();
        ButtonDodaj = new javax.swing.JButton();
        ButtonEdytuj = new javax.swing.JButton();
        ButtonUsun = new javax.swing.JButton();
        ButtonAll = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();

        TabelaDanych.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Miejscowość", "Kod pocztkowy"
            }
        ));
        jScrollPane1.setViewportView(TabelaDanych);

        ButtonDodaj.setText("DODAJ");
        ButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDodajActionPerformed(evt);
            }
        });

        ButtonEdytuj.setText("EDYTUJ");
        ButtonEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdytujActionPerformed(evt);
            }
        });

        ButtonUsun.setText("USUŃ");
        ButtonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUsunActionPerformed(evt);
            }
        });

        ButtonAll.setText("WYŚWIETL WSZYSTKO");
        ButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAllActionPerformed(evt);
            }
        });

        jButton1.setText("FILTRUJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Miejscowość");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEdytuj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(96, 96, 96)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ButtonAll, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonEdytuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonUsun)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDodajActionPerformed
       AddP.setVisible(true);
    }//GEN-LAST:event_ButtonDodajActionPerformed

    private void ButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAllActionPerformed
        // TODO add your handling code here:
        
        Object[] columnNames = {"ID","Miejscowosc","Kod pocztowy"};
        DefaultTableModel DIM = new DefaultTableModel();
        DIM.setColumnIdentifiers(columnNames);
        
         try 
            {   
                Class.forName("oracle.jdbc.OracleDriver");
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                st = con.createStatement();
                String sql = "SELECT * FROM POCZTY";
                Res = st.executeQuery(sql);
                
                
                while(Res.next())    
                {
                    int id_poczty = Res.getInt("ID_POCZTY");
                    String miejscowosc = Res.getString("MIEJSCOWOSC");
                    String kod_pocztowy = Res.getString("KOD_POCZTOWY");
                    
                    Object[] object = {id_poczty,miejscowosc,kod_pocztowy};
                    DIM.addRow(object);
                    
                }
                    
                Res.close();
                st.close();
                con.close();
            }
            catch(Exception e){JOptionPane.showMessageDialog(null, e);}
           
            TabelaDanych.setModel(DIM);   
    }//GEN-LAST:event_ButtonAllActionPerformed

    private void ButtonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUsunActionPerformed
        // TODO add your handling code here:
        if (TabelaDanych.getSelectedRow() != -1) 
        {
             String id_r = (TabelaDanych.getValueAt(TabelaDanych.getSelectedRow(), 0)).toString();
             int a = 0;
             try 
                {
                    Class.forName("oracle.jdbc.OracleDriver");
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
                    st = con.createStatement();
                    //String sql = "SELECT * FROM ODDZIALY_BANKOWE";
                    String sql = "DELETE FROM \"POCZTY\" WHERE \"ID_POCZTY\" = " + id_r;
                    Res = st.executeQuery(sql);
                }
             
             catch(Exception e)
             {
                a = 1;
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Nie można usunąć poczty. Dana poczta jest używana");
             }
         if (a == 0)  {JOptionPane.showMessageDialog(null, "Usunięto poczte");}
        }
        
    }//GEN-LAST:event_ButtonUsunActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            String miejscowosc = jTextField1.getText();
            
            Object[] columnNames = {"ID","Miejscowosc","Kod pocztowy"};
            DefaultTableModel DIM2 = new DefaultTableModel();
            DIM2.setColumnIdentifiers(columnNames);
            
            try
            {
                
                
            Class.forName("oracle.jdbc.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:bank",USER,PASS);
            Statement st = con.createStatement();
            String sql = "SELECT * FROM POCZTY WHERE MIEJSCOWOSC =" + "'"+miejscowosc+"'"; 
            Res = st.executeQuery(sql);
            
            while(Res.next())    
                {
                    int id_poczty = Res.getInt("ID_POCZTY");
                    String miejscowosc1 = Res.getString("MIEJSCOWOSC");
                    String kod_pocztowy = Res.getString("KOD_POCZTOWY");
                    
                    Object[] object = {id_poczty,miejscowosc1,kod_pocztowy};
                    DIM2.addRow(object);
                    
                }
                    
                Res.close();
                st.close();
                con.close();
            
            }
            
             catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            TabelaDanych.setModel(DIM2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdytujActionPerformed
        // TODO add your handling code here:
        if (TabelaDanych.getSelectedRow() != -1) 
        {
        String id_poczty = (TabelaDanych.getValueAt(TabelaDanych.getSelectedRow(), 0)).toString();
        UpDate = new UpdatePoczta(PASS,USER,id_poczty);
        UpDate.setVisible(true);
        
        }
    }//GEN-LAST:event_ButtonEdytujActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAll;
    private javax.swing.JButton ButtonDodaj;
    private javax.swing.JButton ButtonEdytuj;
    private javax.swing.JButton ButtonUsun;
    private javax.swing.JTable TabelaDanych;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
